### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by dgagnon** [AbuseIO/AbuseIO#136]
Hi,

we are currently testing out AbuseIO in our incidence responce workflow and have pin pointed a few areas which really could use some improvement.  Here are our notes so that other may chime in and offer their comments and or suggestions.
1. Tickets page
2. There should be a "Customer Status" column and filter to allow agents to see tickets who can be resolved.
3. Tickets with a reply from the contact should be highlighted.  A column with a filter could also work.
4. A Mass status change could sometimes be useful.
5. Netblocks / domains / contacts
6. Would be useful to see statistics ( i.e. # of open incidents, etc )
7. Analytics page
8. More advance statistics would be welcomed: total opened/closed/resolved/ignored tickets, last 24h/7days/30 days new tickets,

**Comment by kruisdraad** [comment]
We have a 4.1-gui branch with a new GUI including statistics. We will improve on several items which should fit some of these feeds. Please use and test this branch and return feedback on the new GUI.
