### ISSUE TITLE
New parser for inclusion

### ISSUE THREAD

**Issue by jkakavas** [AbuseIO/AbuseIO#150]
Hi, 

Opening this as an issue as I am not sure what the recommended approach is for submitting new parsers for inclusion in core. The parser handles notifications from Sony on account takeover attempts. I've been using this with no issues in our environment for the last 3 months. 

https://github.com/jkakavas/parser-sony

I added a samples dir with 3 sample email notifications, let me know if you need this in a different format.

**Comment by kruisdraad** [comment]
Yeah this is the recommended approach.

Could you please extend your samples to be full EML (the raw e-mail including headers, etc)

**Comment by jkakavas** [comment]
Hi Bart, 

Thanks for the response. Just pushed the eml samples. 

I'm preparing a second parser with samples, I'll add it here too unless you prefer I open another issue.

**Comment by jkakavas** [comment]
The second parser is : https://github.com/jkakavas/parser-nfoservers

**Comment by kruisdraad** [comment]
accepted into upstream.
