### ISSUE TITLE
InvalidArgumentException in C:\wamp64\www\LaravelAPI\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php line 137: View [helo word] not found.

### ISSUE THREAD

**Issue by Noumamayo** [AbuseIO/AbuseIO#187]
when i change the route then this error are show kindly help...

**Comment by kruisdraad** [comment]
What version of AbuseIO are you running?

**Comment by Noumamayo** [comment]
laravel 5.3

**Comment by kruisdraad** [comment]
We do not support Laravel, we support Abuseio

**Comment by Noumamayo** [comment]
thanks (: but sir kindly guide me ... about this type off error

**Comment by kruisdraad** [comment]
Try the Laravel github, forums, chat, etc

we do not support laravel outside the AbuseIO scope
