### ISSUE TITLE
iodef attachment should be compressed

### ISSUE THREAD

**Issue by kruisdraad** [AbuseIO/AbuseIO#197]
$message->attach(Swift_Attachment::newInstance(gzencode($XmlAttachmentData), 'iodef.xml.gz', 'application/gzip'));

**Comment by marknl** [comment]
This is done in notification-mail module.

**Comment by marknl** [comment]
https://github.com/AbuseIO/notification-mail/commit/a8b44ec43b55daa8adf9e096e4a5081880ba0a1b

**Comment by kruisdraad** [comment]
implemented in 1.3.2 which is included in 4.1, but not 4.0

todo: test or fix 4.0

**Comment by kruisdraad** [comment]
fixed with commit in master 1.3 and branch 1.2.x
