### ISSUE TITLE
Disregard reports for IP addresses not in Customer blocks

### ISSUE THREAD

**Issue by jkakavas** [AbuseIO/AbuseIO#20]
Hi, 

Sometimes you subscribe for feeds that are not so configurable that will contain addresses not in your customer ranges. Would it make sense to add an option to disregard these reports ? Of course this can be coded in each parser..

**Comment by kruisdraad** [comment]
It would be possible to decline unknown resolved customers entirely. However sometimes you get a report that is not your IP but perhaps your DNS, Registration service, etc is involved in the matter and is referenced along the way. But it should certainly be an option, as we've seen even google send out reports incorrectly.

Ways to go:
- Define all the known nets in the database (customers/netblocks) or remote (find_customer). If a customer was not resolved then the request will be denied (preferred in my opinion)
- Define all the local nets in the config
- A pruning job implementation that will clear wrongly added IP reports at the housekeeper run.

awaiting other replies from devs before implementation

**Comment by jkakavas** [comment]
Any plans for this ? Maybe a design decision so that we can take a look at it ?

**Comment by kruisdraad** [comment]
Hi,

Yes, for 3.1. Its not a majorly needed feature, as when looked at we're only seeing a 0,0001% false positive based on IP ;)

Its a combination of several things, as for example you dont want to update it every day when you add a new IP space. I've updated BIT's ASCC to be able to output all the IP ranges for an ISP.

In addition we need to look into IPA's was you should always 'resolve' a customer based on IPA and it would be fairly easy to deny request if the IP cannot be resolved. It really depends on the amount of false positive data received that need to be resolved.

We will be implementing filtering in 3.1, but more broaden ... not only based on IP's in your ASN(s) but also the ability to filter specific classes on specific feeds without the need of editing the parser/collector. IT would allow us to filter globally on the incoming events.

At this point were discussing about which direction were taking ... A are we first upgrading to MVC and then continue development or B continue with 3.x for now until we have more core devs that can assist in such a migration.

loads of stuff to do ;) but imho its definatly in the next release.

----- Original Message -----
From: Ioannis Kakavas
[mailto:notifications@github.com]
To: AbuseIO/AbuseIO
[mailto:AbuseIO@noreply.github.com]
Cc: Bart Vrancken
[mailto:bart@abuse.io]
Sent: Tue, 14 Apr 2015 14:17:59 +0100
Subject: Re:
[AbuseIO] Disregard reports for IP addresses not in Customer blocks (#20)

**Comment by kruisdraad** [comment]
Included on the roadmap for deployment in 4.0 branch

**Comment by kruisdraad** [comment]
implemented at 4.0 branch configuration with specification listed for matching engine
