### ISSUE TITLE
validator error - multiple contact addresses with comma-and-whitespace separator

### ISSUE THREAD

**Issue by andrege** [AbuseIO/AbuseIO#232]
If I have a comma and a whitespace as address separators in a contact, for example:
"addr@gmail.com, addr2@hotmail.com",
the following error occurs when parsing a new email ticket:

Jun  7 18:26:50 machine abuseio[30191]: production.INFO: AbuseIO\Parsers\Shadowserver: Parser run completed for module : Shadowserver
Jun  7 18:26:50 machine abuseio[30191]: production.INFO: AbuseIO\Parsers\Shadowserver: : Parser completed with 0 warnings and collected 26 incidents to save
Jun  7 18:26:51 machine abuseio[30191]: production.INFO: AbuseIO\Jobs\IncidentsValidate: Validator has ended without errors
Jun  7 18:26:51 machine abuseio[30191]: production.ERROR: AbuseIO\Jobs\IncidentsSave: Saver has ended with errors ! : DevError: Internal validation failed when saving the Ticket object All ip contact email addresses should be valid.
Jun  7 18:26:51 machine abuseio[30191]: production.ERROR: AbuseIO\Jobs\EmailProcess: Email processor ending with errors. The received e-mail will be deleted from archive and bounced to the admin for investigation

It works when I don't have whitespaces in the list of addresses:
"addr@gmail.com,addr2@hotmail.com"

This could be fixed in /opt/abuseio/app/Providers/ValidationsServiceProvider.php, by trimming whitespaces in the "validation for multiple comma separated e-mails" code.

**Comment by kruisdraad** [comment]
Please provide additional information, e.g. which version you are running.

Are you using the local database or linking and external database.

Trimming in validation is not really correct, it had to be done when the object has been created.

**Comment by andrege** [comment]
I am running version 4.0.1, using a local mysql database.

**Comment by kruisdraad** [comment]
The validation used for the webinterface adding a contact uses the same validation. In addition i just tried to add: 'test@test.nl, test@test.nl' and after adding it it results in a 'test@test.nl,test@test.nl'

did you made the contact manually in the database or some other way then the webinterface

also are you using the latest GIT version of 4.0.1, or did you install the tarbal version?

**Comment by andrege** [comment]
Ok, I have inserted my contacts using a script, directly in mysql database; I have a rather big database of contacts and it would be difficult to insert the contacts manually.

I am using the GIT version.

**Comment by kruisdraad** [comment]
you cannot do it like that you can : 

1. use the CLI and scripted add all the customers, ranges, etc
2. use the API (4.1.0, think its ready) and put objects there
3. use the find-contact method. Its a custom lookup method you can fill in by coding your own lookup. You can lookup in your own (current) database. build the right object and return that within the framework. It only requires a few lines of code in your case.

**Comment by andrege** [comment]
Ok, I will study these options. Thanks for the help !
