### ISSUE TITLE
4.0 -> 4.1 migration api_token column

### ISSUE THREAD

**Issue by casdr** [AbuseIO/AbuseIO#236]
When running ```php artisan migrate``` after checking out on the 4.1 branch, I'm getting the following:

```
  [Illuminate\Database\QueryException]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'api_token' in 'field list' (SQL: update `tickets` set `updated_at` = 2017-07-25 12:26:56, `api_token` = [redacted] where `id` = 1)
```

This is because the [migration](https://github.com/AbuseIO/AbuseIO/blob/4.1/database/migrations/2016_10_11_073630_update_tickets_table.php#L33) updates all tickets, but the code assumes the _api_token_ column already exists.

A workaround is by adding the _api_token_ column manually, then running migrate, then remove it because it'll fail on [update_tickets_table_add_apitoken](https://github.com/AbuseIO/AbuseIO/blob/4.1/database/migrations/2016_11_16_085433_update_tickets_table_add_apitoken.php#L16), and running migrate again.

**Comment by kruisdraad** [comment]
Thank you for your report. We had this problem in the the 4.1 branch too while testing this week. We implemented some changes in migrations and successfully migrated a 4.0 to a 4.1 installation. We also updated the documentation on the upgrade procedure.
