### ISSUE TITLE
New tickets are not getting created

### ISSUE THREAD

**Issue by aarakh** [AbuseIO/AbuseIO#294]
Installation done successfully with PHP 5.6.32.

Abuseio version4.0.0, Found that framework.log was not created in /var/log/abuseio.

Also able to see tickets when imported sample mails, however when tried to create ticket by sending email to notifier@mydomain.com not created any ticket.

Nothing in postfix log of abuseio server.
from sender's logs it shows message delivered

Could you help what goes wrong here?

**Comment by kruisdraad** [comment]
if the log is not created, then it sounds like you have a issue with permissions which stops the framework from starting. Have you checked the php errors logs?

you have to have the framework.log ... perhaps its in your storage/logs/ folder?

**Comment by kruisdraad** [comment]
show ls -all including . and ..

**Comment by aarakh** [comment]
Update on previous comments:
i am able to access framework GUI through URL http://localhost/admin/tickets. Able to see imported sample 24 tickets in GUI.
Also mailarchive successfully archived imported sample tickets.
However framework.log not generated in /var/log/abuseio/

**Comment by kruisdraad** [comment]
can you please check if you added your MTA (postfix?) onto the abuseio group?

you can also  try so su to postfix and try to run the 'run all' samples creator.

also ahve you checked the queues? are your queues running at all, are there failed jobs? etc?

**Comment by aarakh** [comment]
Hi,

tried "run all" samples creator, tickets are created successfully. 
However queue always shows 0 jobs.
Yes, postfix is abuseio group.

Since framework.log was not created , so not able to see any errors/warnings which were generated.
Output:
==========================================
$ php artisan queue:list
+------------------------+------+
| Queue                  | Jobs |
+------------------------+------+
| abuseio_collector      | 0    |
| abuseio_email_incoming | 0    |
| abuseio_email_outgoing | 0    |
+------------------------+------+
$ id postfix
uid=89(postfix) gid=89(postfix) groups=89(postfix),12(mail),10500(abuseio)
$
=============================================

**Comment by aarakh** [comment]
Used below for loop to import sample tickets, these tickets are imported successfully, however jobs shows as zero.

$ for file in `find extra/notifier-samples/feedback-loop/ -type f | sort | grep eml`;do echo $file;cat $file | php -q artisan email:receive;done
extra/notifier-samples/feedback-loop/AOL_example_1.eml
extra/notifier-samples/feedback-loop/AOL_example_2.eml
extra/notifier-samples/feedback-loop/Bluetie_example_1.eml
extra/notifier-samples/feedback-loop/Bluetie_example_2.eml
extra/notifier-samples/feedback-loop/Comcast_example_1.eml
extra/notifier-samples/feedback-loop/Comcast_example_2.eml
extra/notifier-samples/feedback-loop/Cox_example_1.eml
extra/notifier-samples/feedback-loop/Cox_example_2.eml
extra/notifier-samples/feedback-loop/Fastmail_example_1.eml
extra/notifier-samples/feedback-loop/Fastmail_example_2.eml
extra/notifier-samples/feedback-loop/OpenSRS_example_1.eml
extra/notifier-samples/feedback-loop/OpenSRS_example_2.eml
extra/notifier-samples/feedback-loop/Rackspace_example_1.eml
extra/notifier-samples/feedback-loop/Rackspace_example_2.eml
extra/notifier-samples/feedback-loop/RoadRunner_example_1.eml
extra/notifier-samples/feedback-loop/RoadRunner_example_2.eml
extra/notifier-samples/feedback-loop/Synacor_example_1.eml
extra/notifier-samples/feedback-loop/Synacor_example_2.eml
extra/notifier-samples/feedback-loop/USANet_example_1.eml
extra/notifier-samples/feedback-loop/USANet_example_2.eml
extra/notifier-samples/feedback-loop/Yahoo_example_1.eml
extra/notifier-samples/feedback-loop/Yahoo_example_2.eml
extra/notifier-samples/feedback-loop/Zoho_example_1.eml
extra/notifier-samples/feedback-loop/Zoho_example_2.eml
$ php artisan queue:list
+------------------------+------+
| Queue                  | Jobs |
+------------------------+------+
| abuseio_collector      | 0    |
| abuseio_email_incoming | 0    |
| abuseio_email_outgoing | 0    |
+------------------------+------+
$

**Comment by aarakh** [comment]
Update:
Observed that:
framework.log file was successfully created on test machines on which PHP > 7.0.

However for PHP 5.6, framework.log file was not created in /var/log/abuseio/

**Comment by kruisdraad** [comment]
The Jobs only show pending jobs, so it can be that the tickets have been processed. If you see the tickets then its all good.

Regarding the logfile, it should be in /var/log/ if you entirely followed the manual. If not, it might be in the insallation directory under storage/logs/ you can check the config file on the exact location. Please note that if you have used 'abuseio' as the user ... that user has to have access to create and update the logfile, this might be missing?

If the logfile cannot be created/updated the GUI is likely not working and just gives a empty white page. If you can login and see the ticket, then the logfile has to be somewhere.

**Comment by aarakh** [comment]
Thanks for reply,
I think i figured out logfile issue, its some thing related to syslog daemon.
However still new tickets are not getting created after sending email to feedback@mydomain.com or  notifier@mydomain.com. If you could help with this issue.
