### ISSUE TITLE
Logging is no longer working

### ISSUE THREAD

**Issue by kruisdraad** [AbuseIO/AbuseIO#296]
laravel refuses to log, to file, syslog or any other option

**Comment by WeszNL** [comment]
Is there any fix for this? Would be nice to have some logging.

**Comment by marknl** [comment]
This is an old ticket. Logging works fine.
Also, logging to syslog is forced here:
https://github.com/AbuseIO/AbuseIO/blob/master/bootstrap/app.php#L47
https://github.com/AbuseIO/AbuseIO/commit/0e0516492b2c69be1eea72d449df6f448a653cee#diff-adb5c22958ced30038e92c8ceb2f2871

**Comment by WeszNL** [comment]
note: I had to switch from systemd to supervisor to get logging working.

**Comment by webtel** [comment]
I also seem to have this issue - latest install using ansible
