### ISSUE TITLE
Shadowserver reports are not being parsed

### ISSUE THREAD

**Issue by cliffalbert** [AbuseIO/AbuseIO#297]
Shadowserver reports are not being parsed. At first I found out that the content-type is not application/octet-stream but I am receiving them as application/zip. 

diff: https://os2warp.nl/index.php?p=fwfCHA2OSHBwrCkVgXgEWFWd

After changing that in the shadowserver parser code I get the following error:

error: https://os2warp.nl/index.php?p=BWCTxkLwGM9o65Bk1YaoJpFz

**Comment by kruisdraad** [comment]
H Cliff,


Can you tell us what version are you running (dev-master, specific tar from site, etc) ? Also some info on your host would be handy (OS, php version, etc) On my latest dev-version i don't see any 'count'  grep 'app/Models/Account.php' app/Models/Account.php -> 0


Regarding the code change, the zip seems to be really wrapped as:


--b1_d71cf4c505bd9a20eae14b91eda061c9
Content-Type: application/octet-stream; name="2015-01-01-sinkhole_http_drone-sample-asn.csv.zip"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=2015-01-01-sinkhole_http_drone-sample-asn.csv.zip


So could it be that you are forwarding the e-mail or something in such a manor the type was changed in between? The code is just an extra safeguard and can be modified as you did without problems though.

**Comment by cliffalbert** [comment]
It might be that some mailserver in between intervenes (virusscanner etc).

I'm running the stable release from composer. But I already figured out what the problem might be. The stable version uses an old laravel framework which is not compatible with PHP 7.2

**Comment by kruisdraad** [comment]
Ah yes, max version is PHP 7.1

**Comment by marknl** [comment]
AbuseIO is currently being upgraded to Laravel 5.6 which supports PHP 7.2
