### ISSUE TITLE
Customers and Report View in testing AbuseIO

### ISSUE THREAD

**Issue by aarakh** [AbuseIO/AbuseIO#306]
Hi,
Installed AbuseIO 4.0.1, in VirtualBox Setup. After initial setup, observed that Customers and Report View are missing in portal's main window.

Is there any option/way to enable these options in portal login?

I referenced below screenshots. 
https://abuse.io/resources/screenshots/

**Comment by kruisdraad** [comment]
Could you please confirm exactly what you have installed? Also if there are any errors listed in your errors logs?

Finally, you might be better off installing the latest master, as its more up to date.

**Comment by marknl** [comment]
Hi, some labels have changed in a past update.
"Customers" is now called "Contacts" and "Reports" is now called "Analytics".
