### ISSUE TITLE
FBL from editor@returnpath.com are changing

### ISSUE THREAD

**Issue by bslavin** [AbuseIO/AbuseIO#307]
Per an email from editor@returnpath.com they are changing the sending domains for FBLs. 

![image](https://user-images.githubusercontent.com/838505/49044123-bedc8b80-f181-11e8-917d-1e2bba06acf7.png)

**Comment by marknl** [comment]
Hi there, thank you for notifying!

Do you happen to have a complete list (that's not an image ;-). I'd be happy to update the parser with the new addresses.

**Comment by bslavin** [comment]
I can type them.. 

feedbackloop@bluetiefbl.senderscore.net
feedbackloop@coxfbl.senderscore.net
feedbackloop@localwebfbl.senderscore.net
feedbackloop@rackspacefbl.senderscore.net
feedbackloop@synacorefbl.senderscore.net
feedbackloop@terrafbl.senderscore.net
feedbackloop@usanetfbl.senderscore.net
feedbackloop@italianonlinefbl.senderscore.net
feedbackloop@telnorfbl.senderscore.net
feedbackloop@xs4allfbl.senderscore.net

**Comment by marknl** [comment]
I figured there were more. Thanks!

**Comment by marknl** [comment]
https://github.com/AbuseIO/parser-fbl/commit/6661cf885f0dd76a7847d9e7b686eb46d46bf8a7
