### ISSUE TITLE
All configuration files missing [Docker build]

### ISSUE THREAD

**Issue by tcammcom** [AbuseIO/AbuseIO#308]
Hello,

I am attempting to install and configure this on Docker for use with pulling data from ShadowServer.  I have followed the documentation but it appears all of the configuration files,  collectors, and parsers configs are all missing on the filesystem.  I cannot find these files on the git repo either.  

The version of Abuse.IO is   "4.1.0 No update"

Thanks,
Travis

**Comment by kruisdraad** [comment]
if you follow the docs from docs.abuse.io you will have a full installation.

collectors and parsers and modules that are added onto abuseio and installed using the guide and/or install scripts like composer. The are to be installed in the vendor/abuseio/ dir
