### ISSUE TITLE
Outgoing mail always uses SMTP

### ISSUE THREAD

**Issue by yakatz** [AbuseIO/AbuseIO#310]
`.env` includes an option to choose the outgoing mail driver, but https://github.com/AbuseIO/notification-mail/blob/master/src/Mail.php always uses the SMTP driver. I would be happy to change this to use the Laravel Facade (as soon as the 5.6 or 5.7 upgrade is done).

**Comment by kruisdraad** [comment]
AbuseIO 4.3 uses the new Laravel.
