### ISSUE TITLE
MCrypt is deprecated 

### ISSUE THREAD

**Issue by jviersel** [AbuseIO/AbuseIO#312]
The mcrypt functions in PHP are deprecated since PHP 7.1 and removed in 7.2. Also, PHP 7.1 only gets security fixes; PHP 7.2 is the advised version to use. AbuseIO is still using mcrypt, so running an older PHP version is required to get AbuseIO running.

Please replace the mcrypt functions and constants by the OpenSSL functions.

**Comment by kruisdraad** [comment]
thank you, however this is a duplicate.

We have changed the upper requirements to 7.1 so you cannot use abuseio with 7.2 at this time. in the next releases we will be rewriting into the latest laravel framework which removes these old methods and switch to 7.2.

**Comment by jviersel** [comment]
Please make composer.json match these requirements. Currently it says`"php": ">=5.5.9"`. If you change this to, for example, `"php": ">=5.5.9,<7.2.0",`, composer will warn about the unsupported PHP 7.2. Now we have to find out after installation and debugging.

**Comment by marknl** [comment]
> Please make composer.json match these requirements.

Anxiously awaiting your PR .. ;-)
