### ISSUE TITLE
Migration from 4.0 to 4.1

### ISSUE THREAD

**Issue by aarakh** [AbuseIO/AbuseIO#313]
While doing migration from 4.0 to 4.1 , I followed steps given in https://docs.abuse.io/en/latest/migration/.

4.0 to 4.1 Migration was successful. 

After migration found that found that additional table "ticket_graph_points" added in 4.1, which has missing analytics data.

How to make use of "ticket_graph_points" table for existing 4.0  DB data ?

**Comment by kruisdraad** [comment]
if you run php artisan migration it should add all added/changed migrations

**Comment by aarakh** [comment]
Yeah, i executed "php artisan migrate" command, it created that table as per 4.1, however that table is blank, without any values.

**Comment by kruisdraad** [comment]
but the table is there? and its elements? just no data?

you prolly need to run a job for that, but @henkpoldergraaf might know which

**Comment by aarakh** [comment]
"php artisan migrate" -- command creates a required table with required columns, however no data related to existing tickets.

{code}
MariaDB [abuseio]> select * from ticket_graph_points;
Empty set (0.00 sec)

MariaDB [abuseio]>
{code}

**Comment by marknl** [comment]
https://github.com/AbuseIO/AbuseIO/blob/da2fa10ad6252f526ec8c2949526df9800179e12/config/main.php#L56
It looks like it's a housekeeper job which is currently commented.
Regards,Mark

**Comment by henkpoldergraaf** [comment]
Could you please reply if this issue is fixed with the comment made by Mark.

If not I can have a look at this on Monday.

Regards,
Martin

**Comment by aarakh** [comment]
Thanks Mark,

I checked in config/main.php , given line L56 is un-commented.
{code}
 55         'notifications_cron'              => '*/15 * * * * *',
 56         'collectors_cron'                 => '*/60 * * * * *',
 57         'housekeeper_cron'                => '*/1 * * * * *',
 58         'collect_statistics_cron'         => '0 2 * * * *', //needs some discussion on when to run;
 59         'enable_queue_problem_alerts'     => true,

{code}

**Comment by aarakh** [comment]
And I am using default main.php, environment (prod/DEV) customization NOT done. tickets DB table has default tickets which were imported from "extra"

**Comment by marknl** [comment]
Hi @aarakh Can you make sure the line I pointed to before is uncommented and housekeeper is restarted? (the process that runs under supervisord)

**Comment by aarakh** [comment]
yeah, I housekeeper restarted with that "line" un-commented.
And able to fetch details from table "ticket_graph_points.

Closing this issue as solved

**Comment by kruisdraad** [comment]
todo: update common issues

**Comment by aarakh** [comment]
after migration, I tried to import sample feedback loops from /opt/abuseio/extra/notifier-samples/feedback-loop ,

However seen below error in framework.log
`development.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'AbuseIO\Hook\Common' not found in /opt/abuseio/app/Observers/TicketObserver.php:37`

After cheking /opt/abuseio/app/Observers/TicketObserver.php , there is call for "Hooks" , Hook directory is missing in /opt/abuseio/app

**Comment by marknl** [comment]
Common Hooks should be located in the ```vendor/abuseio/hook-common``` folder.
