### ISSUE TITLE
Upgrade doc - missing step

### ISSUE THREAD

**Issue by realasmo** [AbuseIO/AbuseIO#314]
Hello,

Seems that the doc at https://docs.abuse.io/en/latest/migration/ is missing the step:

cd /opt/abuseio ; php artisan migrate

**Comment by imme-emosol** [comment]
Perhaps suggest the change in this file (and/or make a pull-request for the change) :
https://github.com/AbuseIO/abuseio-docs/blob/master/docs/migration.md

**Comment by kruisdraad** [comment]
Updated documentation
