### ISSUE TITLE
Analytics screen does not work

### ISSUE THREAD

**Issue by webtel** [AbuseIO/AbuseIO#316]
I have a new install of AbuseIO via Ansible and it seems that Analytics screen is not functioning. None of the options are clickable  nor is there a way to enter a date range or do other filtering.
I have tried in Chrome and Safari.

**Comment by marknl** [comment]
Hi,
Enable the cron for housekeeper please:
https://github.com/AbuseIO/AbuseIO/blob/da2fa10ad6252f526ec8c2949526df9800179e12/config/main.php#L56

**Comment by webtel** [comment]
Hi

cron is not hashed out in my file as you can see - but analytics screen is still non functional (show graph button doesnt work, none of the fields can be selected or changed)
 'housekeeping' => [
        'mailarchive_remove_after'        => '500 days',
        'mailarchive_remove_orphaned'     => true,
        'tickets_close_after'             => '14 days',
        'closed_tickets_remove_after'     => false,
        'closed_tickets_remove_permanent' => false,
        'notifications_cron'              => '*/15 * * * * *',
        'collectors_cron'                 => '*/60 * * * * *',
        'housekeeper_cron'                => '*/1 * * * * *',
        'collect_statistics_cron'         => '0 2 * * * *', //needs some discussion on when to run;
        'enable_queue_problem_alerts'     => true,
    ],

**Comment by marknl** [comment]
Have you restarted the supervisord processes? I think you need to do that also.
@henkpoldergraaf Could you shed some light on this?

**Comment by webtel** [comment]
Yeah - have even gone so far as rebooting the server :-)

**Comment by marknl** [comment]
Analytics run once a day (0 2 * * * *) .. you could try and change those values to something like:
*/5 * * * *

**Comment by webtel** [comment]
Hi all

My analytics page is still static and drop down boxes cannot even be selected. Is an additional module required to make that page functional ?

**Comment by marknl** [comment]
Do you have records in the table: ticket_graph_points ?

**Comment by webtel** [comment]
Hi There

I do have data in that table.

Regards
Tony Da Silva
Web Telecom Services (PTY) Ltd

**Comment by webtel** [comment]
Hi Guys
Just thought a screenshot might help. 

The section at the bottom of the page doesn’t work - ie - you cannot click dropdown box for lifecycle, From, Till. Classification etc.
The blue show graph button doesn't work / click.

**Comment by webtel** [comment]
Does anybody have advise yet on how to get analytics screen to be functional ?

**Comment by marknl** [comment]
The graphs run on echarts, javascript. Those fields are being created on sight. If they're all disabled, there's something broken in the background. I've tested this on my 4.1 production setup and graphs work fine and I'm able to select different values from the pull downs and display other graph data.

1. If you view the source of the analytics page in your browser, and search for: name="s_class_options" Does it contain any options?
2. When you press CTRL+SHIFT+I (Inspect), open the "Console" tab and reload the page:
2.1. Do you see errors in the console?
2.2. Do you see errors appear in the console when you click the blue button "Show graph"?

**Comment by webtel** [comment]
Hi

Is there a fix yet for this issue?

**Comment by marknl** [comment]
1. Every time you add a comment, you post your api auth key and unsubscribe tokens etc etc.
2. It works on multiple instances I use, so it's likely a core issue.
3. I asked questions, .. still waiting on some answers.

**Comment by webtel** [comment]
Hi Mark

I have previously replied to the questions via email to the list but will paste here again:

1. If you view the source of the analytics page in your browser, and search for: name="s_class_options" Does it contain any options?

`<select class="form-control" id="classification" name="s_class_options"><option value="" selected="selected">`

When you press CTRL+SHIFT+I (Inspect), open the "Console" tab and reload the page:
2.1. Do you see errors in the console?
```
analytics:155 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-2H9C0R2BPUv+SxrOTXEyB5xRV6n2DHMQnCdxoT0Maxs='), or a nonce ('nonce-...') is required to enable inline execution.

analytics:200 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-xxxxxxxxxxxs='), or a nonce ('nonce-...') is required to enable inline execution.

30Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self'".
```

(Note, I removed the hash from analytics:200 line)

2.2. Do you see errors appear in the console when you click the blue button "Show graph"?
The blue show graph button cannot be pushed.

**Comment by marknl** [comment]
I get 0 errors. Check that you don't force incorrect headers in your vhost setup. Also make sure you're not blocking some content with a browser extension.

**Comment by webtel** [comment]
Hi. Any feedback on this problem yet?

**Comment by webtel** [comment]
Hello

Sorry for late reply. I am not forcing any headers in vhost setup and have no browser extensions that blocks content. I have tested on multiple machines and browsers and see the same thing.

**Comment by marknl** [comment]
I'm unable to reproduce the issue, so I can't fix it. 
Just for funzies, setup a fresh AbuseIO installation according to the documentation, see if the issue happens on a fresh setup.

**Comment by pettai** [comment]
I think https://github.com/AbuseIO/AbuseIO/issues/349 might be the same issue
it's a fresh docker-based install, and from what I can see, what @webtel wrote seems to be on par on my abuseio-docker installation too.
I can walk-thru all steps to just to be sure.

**Comment by pettai** [comment]
https://github.com/AbuseIO/AbuseIO/pull/355 fixes this
