### ISSUE TITLE
AbuseIO was not able to process a collection.

### ISSUE THREAD

**Issue by WeszNL** [AbuseIO/AbuseIO#325]
Every hour we receive the following message:
AbuseIO was not able to process a collection. This the logs for PID:1535

framework.log:
Apr 10 19:00:21 abuseio abuseio[1535]: production.ERROR: AbuseIO\Jobs\IncidentsSave: Saver has ended with errors ! : Unable to link to ticket, multiple open tickets found for same incident type
Apr 10 19:00:21 abuseio abuseio[1535]: production.ERROR: AbuseIO\Jobs\CollectorProcess: Collector processor ending with errors.

How do I find out which ticket(s) is/are causing this and how would I resolve this?

**Comment by kruisdraad** [comment]
You can check the logs for the ID 1535 and see which EML is being processed (or check the queue for an old job that repeats over and over again). This will show the IP ... then you can do a SQL query to find the duplicates and chose one to close.

This useally happens and a abuse employee opens an old case, but a new case was generated. At this time there is no way (yet) to merge them. It is listed on the roadmap to resolve this.

**Comment by WeszNL** [comment]
Unfortunately logging only works for framework.log and only when using supervisor.
queue_collector.log, queue_delegation.log, queue_email_incoming.log & queue_email_outgoing.log are always empty.

Is there another way to see which EML is being processed or a method to enable logging?
