### ISSUE TITLE
AbuseIO fails to work on Ubuntu 18.04 LTS and PHP 7.2

### ISSUE THREAD

**Issue by aajump** [AbuseIO/AbuseIO#332]
Ever since updating to Ubuntu 18.04 LTS the webpage just display  "Whoops, looks like something went wrong." and looking through the logs (copied below) shows an error related to the wrong encryption cipher.

After looking at similar issues in the laravel issue tracker, it seems that PHP 7.2 removes older ciphers that Laravel used. i've tried adding APP_CIPHER=AES-256-CBC to the .env file to make it use a newer cipher but it hasn't helped.

does anyone have a resolution for this issue?

OS: Ubuntu 18.04.3 LTS
PHP Version: PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )
AbuseIO version: 4.1.0

Log Output:
Sep  3 17:07:01 abuseio abuseio[12100]: production.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /opt/abuseio/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:29 
Stack trace: 
#0 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array) 
#1 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure), Array) 
#2 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('encrypter', Array) 
#3 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(1167): Illuminate\Foundation\Application->make('encrypter') 
#4 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(117): Illuminate\Container\Container->offsetGet('encrypter') 
#5 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/QueueServiceProvider.php(69): Illuminate\Queue\QueueManager->connection() 
#6 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): Illuminate\Queue\QueueServiceProvider->Illuminate\Queue\{closure}(Object(Illuminate\Foundation\Application), Array) 
#7 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure), Array) 
#8 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('queue.connectio...', Array) 
#9 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(1167): Illuminate\Foundation\Application->make('queue.connectio...') 
#10 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Bus/BusServiceProvider.php(25): Illuminate\Container\Container->offsetGet('Illuminate\\Cont...') 
#11 [internal function]: Illuminate\Bus\BusServiceProvider->Illuminate\Bus\{closure}() 
#12 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(234): call_user_func(Object(Closure))
#13 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(175): Illuminate\Bus\Dispatcher->dispatchToQueue(Object(AbuseIO\Jobs\QueueTest)) 
#14 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(AbuseIO\Jobs\QueueTest)) 
#15 /opt/abuseio/app/Console/Commands/Housekeeper/RunCommand.php(172): AbuseIO\Console\Commands\Housekeeper\RunCommand->dispatch(Object(AbuseIO\Jobs\QueueTest)) 
#16 /opt/abuseio/app/Console/Commands/Housekeeper/RunCommand.php(60): AbuseIO\Console\Commands\Housekeeper\RunCommand->checkQueues() 
#17 [internal function]: AbuseIO\Console\Commands\Housekeeper\RunCommand->handle() 
#18 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array) 
#19 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array) 
#20 /opt/abuseio/vendor/symfony/console/Command/Command.php(238): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#21 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#22 /opt/abuseio/vendor/symfony/console/Application.php(840): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#23 /opt/abuseio/vendor/symfony/console/Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(AbuseIO\Console\Commands\Housekeeper\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#24 /opt/abuseio/vendor/symfony/console/Application.php(114): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#25 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#26 /opt/abuseio/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#27 {main}

**Comment by kruisdraad** [comment]
please retest against the 4.3.0 branch and report back. These issues look related to the outdated laravel framework which is fixed in 4.3.0.
