### ISSUE TITLE
Microsoft office 365 email parse -> fetchmail and postfix config?

### ISSUE THREAD

**Issue by iderbukh** [AbuseIO/AbuseIO#341]
Microsoft office 365 email parse -> fetchmail and postfix config?

**Comment by iderbukh** [comment]
How to configure "fetchmail" for Office 365?

**Comment by kruisdraad** [comment]
please dont spam tickets, we will reply once we have the time to do so. This tracker is meant to report issues, if you want to ask support questions please use the mailing list and/or IRC chat.

There is no guide available of O365, we suggest creating a new sublabel in DNS for this server and use this for the mail domain as well.
