### ISSUE TITLE
AbuseIO 4.2 - Analytics ticket graph (and filters are) broken

### ISSUE THREAD

**Issue by pettai** [AbuseIO/AbuseIO#349]
The Analytics ticket Graph "Total new per day" is not displaying anything
And the drop-down lists `Classification`, `Type` and `Status` are just showing "Please select" as the only option.

![Screen Shot 2020-06-08 at 06 20 27](https://user-images.githubusercontent.com/3317462/83992381-71cd9e00-a950-11ea-9c56-cd96afbdda9f.png)

There is lots of tickets in the system and a few are import the same day, so those should be visible at the default timeline 
![Screen Shot 2020-06-08 at 06 28 05](https://user-images.githubusercontent.com/3317462/83992755-a2fa9e00-a951-11ea-9cad-bea015fa5905.png)

**Comment by pettai** [comment]
https://github.com/AbuseIO/AbuseIO/pull/355 fixes this

**Comment by kruisdraad** [comment]
please retest against the 4.3.0 branch and report back. These issues look related to the outdated laravel framework which is fixed in 4.3.0.
