### ISSUE TITLE
Add demo setting

### ISSUE THREAD

**Issue by kruisdraad** [AbuseIO/AbuseIO#35]
In demo mode (demo.abuse.io, but also demonstrations) it would be handy to anonymize some of the data shown like the IP into 213.213.x.x and hide customer information after the first letter.

**Comment by ihatehandles** [comment]
So many many ways to modify the data and mask it like that. What did you have in mind?

**Comment by kruisdraad** [comment]
enough samples have been provided now to fill abuseio with data, same goal has been reached with a different method.
