### ISSUE TITLE
RFE - "Auto-close" outdated Tickets (based on "Last seen")

### ISSUE THREAD

**Issue by pettai** [AbuseIO/AbuseIO#352]
In an big, dynamic environment, where you ingest a lot of automated reports, some of them becomes fixed by them selves sooner or later, before the customer is contacted (number of Events stops counting up and the Last seen timestamp stops updating).

Based on that, it would be nice to be able to let AbuseIO Auto-close those Tickets based on a fixed date/time counter. Either with a new status "auto-closed", or just closing the ticket + adding a comment that the system auto-closed the ticket because it passed the no-activity window. 

I would suggest an auto-close window at 14 days of inactivity on "Last seen".

**Comment by kruisdraad** [comment]
This is already available and can be set in the configuration files.
