### ISSUE TITLE
Stable (non-dev) release for abuseio/findcontact-nipap

### ISSUE THREAD

**Issue by pettai** [AbuseIO/AbuseIO#353]
Since abuseio/findcontact-nipap hasn't been released as a normal (non-dev) release, it can't be installed with the default composer.json's [minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability), which has to be changed to "dev" (which will have other side-effects). Please consider releasing findcontact-nipap as a non-dev release.

**Comment by kruisdraad** [comment]
We can only do this if we have enough feedback from users saying they are using it and its stable. Manual install should still be possible by requiring this module only at the latest /master version. If there is a conflict please post the entire logs so we can have a look to reproduce it.

**Comment by kruisdraad** [comment]
Now deployed as stable version 1.0.2
