### ISSUE TITLE
Parsing E-mails that are forwarded from the same address

### ISSUE THREAD

**Issue by koakenred** [AbuseIO/AbuseIO#356]
I have recently installed AbuseIO on one of our servers, but i am running into an issue. When i try to forward e-mails (for example from: netcraft and Shadowserver) to our AbuseIO server, according to /var/log/messages the Shadowserver e-mail is parsed as an netcraft e-mail. This is probably because i configured the address from which i am forwarding in the sender map for both the Netcraft and Shadowserver parsers. Besides changing the sender map, i also changed the body_map to contain something from the e-mail body of the Netcraft and Shadowserver e-mails. But this seems to be ignored when parsing. 

How could i fix this? Or is there a different way to differentiate e-mails with the same sender_map in the parser?

**Comment by kruisdraad** [comment]
you should NOT forward these emails, this will not work simply by changing the mappings. I suggest you *bounce* the messages from your origin or your email fetching from your mailbox ... or using multiple aliases to shift the mail in the right boxes. The body map does work, but it needs to be unique, and not related to headers as its a *body map*

Also this is not a support channel, this is not a bug report. If you want support, please use the mailing list or the IRC channel.
