### ISSUE TITLE
ipechelon/copyrightnotice: filters broken 

### ISSUE THREAD

**Issue by mikenowak** [AbuseIO/AbuseIO#367]
@kruisdraad 

It appears that filters for both ipechelon and copyrightnotice parsers are broken.

Let's look at ipechelon, as copyright notice appears to share a lot of code with it.

Firstly, the following filters are set in the config:

https://github.com/AbuseIO/parser-ipechelon/blob/4cfc1b9e1472e6c98d93df7556d4cedccbdb9fe3/config/Ipechelon.php#L28-L32

Primo, all of these are outside of `$report_raw['Source']` which we apply filters to

https://github.com/AbuseIO/parser-ipechelon/blob/4cfc1b9e1472e6c98d93df7556d4cedccbdb9fe3/src/Ipechelon.php#L87

And then we finally save the `$report_raw`, completely ignoring `$report`.

https://github.com/AbuseIO/parser-ipechelon/blob/4cfc1b9e1472e6c98d93df7556d4cedccbdb9fe3/src/Ipechelon.php#L98

I am happy to fix these but want to understand what we want to collect for the incident.

Here is an example of what is currently saved, but the use of `$report_raw['Source']` above is quite confusing, so I am not sure what was the intention here. Can you clarify what you've intended to capture and what should be ignored?

```
Case ID: [redacted]
Case Status: Open
Case Severity: Normal
Complainant Entity: Paramount Pictures Corporation
Complainant Contact: IP-Echelon - Compliance
Complainant Address: 6715 Hollywood Blvd Los Angeles CA 90028 United States of America
Complainant Phone: +1 (310) 606 2747
Complainant Email: p2p@[redacted]
Service_Provider Entity: [redacted]
Service_Provider Email: abuse@[redacted]
Source TimeStamp: 2020-03-12T19:02:00Z
Source IP_Address: [redacted]
Source Port: 54599
Source Type: BitTorrent
Source SubType @attributes: This is filtered due to fourth layer nesting
Source Number_Files: 1
Content Item TimeStamp: 2020-03-12T19:02:00Z
Content Item Title: Sonic the Hedgehog
Content Item FileName: Sonic The Hedgehog (2020) [1080p] [WEBRip] [YTS.MX]
Content Item FileSize: 1772912495
Content Item Hash: f3acfd3979cc1a30cc7f312673ced688ce78ce77
```

**Comment by kruisdraad** [comment]
fixed in version 3.0.9
