### ISSUE TITLE
Exception notification for complaints from staff@hotmail.com

### ISSUE THREAD

**Issue by webtel** [AbuseIO/AbuseIO#368]
Hi all

Is AbuseIO able to process spam complaints from Microsoft?
The mails are simply forwarded to my email address as an attachment and not processed by AbuseIO with a ticket created.

**Comment by mikenowak** [comment]
these Hotmail notifications are not a standard feedback loop style emails, for this, you would need AbuseIO/parser-jmrp which isn't in core just yet

**Comment by kruisdraad** [comment]
Github issues are not the place for questions, please use our mailinglists.
