### ISSUE TITLE
NBIP Packages contribution

### ISSUE THREAD

**Issue by SandereNBIP** [AbuseIO/AbuseIO#371]
Hi AbuseIO team,

As some of you are probably aware NBIP.nl is using the Abuseio for the cleannetworks.net initiative. 
We've added and made changes for our own use, some of which may be useful for the core team aswell. Below a short list of functionality we've added which may be useful as packages or to be intergrated into the core:
- Shadowserver parser expansion for a number of reports. We will put in a PR for this. 
- Text to go along with the shadowserver parser expansion for the classification files (Dutch & English).
- A front-end solution to create & manage roles within Abuseio (i.e. manage roles to make certain menu items and the pages behind those items available or unavailable based on roles assigned to the user).
- New user notification (send the new user an e-mail when added to an instance with functionality to change the password on first login).

Could you let us know which packages/features could be useful for you guys? We can always discuss what would be the best way to help integrate it for you guys.

Currently, only the Shadowserver expansion will have a PR, since the rest of the packages are currently on our own GIT environment and are a bit harder to pull request your way!

Kind Regards,
Sander

**Comment by SandereNBIP** [comment]
The Shadowserver addition PR : https://github.com/AbuseIO/parser-shadowserver/pull/5

**Comment by kruisdraad** [comment]
The item 2 (texts) are part of AbuseIO core ... you will need to push these first before we can accept the new parser.

**Comment by kruisdraad** [comment]
added
