### ISSUE TITLE
Add parser ' Class 'AbuseIO\Parsers\Sony' not found'

### ISSUE THREAD

**Issue by seraus09** [AbuseIO/AbuseIO#372]
Hello. I try to add new parser of Sony, i cloned it into /opt/abuseio/vendor/abuseio/ and did 
php artisan cache:clear
php artisan clear-compiled
php artisan optimize

but when i want to test it cat vendor/abuseio/parser-sony/samples/sample1.eml | php -q artisan email:receive --noqueue
I get error. Can you help to solve this situation.

 production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'AbuseIO\Parsers\Sony' not found in /opt/abuseio/vendor/abuseio/parser-common/src/Factory.php:92 Stack trace: #0 

Parser https://github.com/jkakavas/parser-sony/blob/master/src/Sony.php

**Comment by kruisdraad** [comment]
This is not the correct way of installing parners, please use composer to install it.

Also your commands does not include restarting daemons, please look in the 'creating a new parser' guide for additional information on how to do this.

Please use the mailing list for support related questions, this is not a bug or issue.

**Comment by seraus09** [comment]
Could you please ask how to do it, but i try to do all from instruction but
no result the error is the same?

**Comment by seraus09** [comment]
And sorry for  my issue
