### ISSUE TITLE
Use of Predictable Algorithm in Random Number Generator

### ISSUE THREAD

**Issue by DEV696** [AbuseIO/AbuseIO#381]
**Description**
Insecure randomness errors occur when a function that can produce predictable values is used as a source of randomness in security-sensitive context. 
In this case the function that generates weak random numbers is rand() in generatePassword.php at line 9.

**Affected Instance**
https://github.com/AbuseIO/AbuseIO/blob/9e661fd75a232d78c31c99694d0b654dd9443571/app/Helpers/generatePassword.php#L9

**Impact**
The random number generator implemented by mt_rand() cannot withstand a cryptographic attack, it is easy for an attacker to guess the strings it generates.

**Comment by kruisdraad** [comment]
Searching a repo and claiming that rand() is bad without understand the underlying code, only create false reports. The way we use this method it is not an security problem.
