### ISSUE TITLE
Error during php artisan migrate

### ISSUE THREAD

**Issue by RobinDev03** [AbuseIO/AbuseIO#386]
Hey, I'm trying to install AbuseIO on my Ubuntu 22.04 Server. After fillign th database credentials to the .env-File I un into this error during php artisan migrate...

https://paste.robin-it.group/fedakobeve.rb

**Comment by kruisdraad** [comment]
could it be you skipped a few steps? looks like the laravel submodules were never installed

**Comment by kruisdraad** [comment]
no replies, close
