### ISSUE TITLE
Tag latest commit with version 3.0.8 in abuseio/parser-shadowserver

### ISSUE THREAD

**Issue by iTeV** [AbuseIO/AbuseIO#391]
Hi,

Creating this issue here since I can't create issues in https://github.com/abuseio/parser-shadowserver :)

Is it possible to tag the latest commit in https://github.com/abuseio/parser-shadowserver with version `3.0.8`? Composer still fetches the `3.0.7` tag. That tag dates to a commit in june 2020. Somewhat out-of-date, alot of feeds has been added since then :P

**Comment by kruisdraad** [comment]
To github.com:AbuseIO/parser-shadowserver.git
 * [new tag]         3.0.8 -> 3.0.8
