### ISSUE TITLE
Parsers for nbip and DTRC available

### ISSUE THREAD

**Issue by HA-TB303** [AbuseIO/AbuseIO#402]
Hi, does anybody have working parsers for NBIP and DTC? If so, could you kindly share? It fees silly to reinvent the wheel. If not, we will put some time in it.  ;)

**Comment by kruisdraad** [comment]
This is not a forum, but to report issues. 

As far as i know NBIP uses AbuseIO, so chaining of tickets is even possible , the AbuseIO-Notification by default adds an attachment that can be parsed again by AbuseIO (and other platforms understanding IODEF). 

For DTC there is nothing as far as i know. In general the data is sourced from other platforms (e.g. shadowserver) and therefor redundant/unneeded. We can always add your provided code, however unless they actually provide something unique and useful it would not be added/enabled by default.

**Comment by HA-TB303** [comment]
Thanks for responding. I wam aware of that, but as I was unable to find a forum, this seemed to be the only option.
