### ISSUE TITLE
Branding templates

### ISSUE THREAD

**Issue by marknl** [AbuseIO/AbuseIO#41]
I'd like to have a branding possibility in the product. A brand contains some basic information like company name, contact info, logo and ash template.

The relations would be:
Netblock->hasOne('AbuseIO\Models\Brand')
Domain->hasOne('AbuseIO\Models\Brand')

Brand->hasMany('AbuseIO\Models\Netblock')
Brand->hasMany('AbuseIO\Models\Domain')

**Comment by kruisdraad** [comment]
Branding has a place inside ASH, as its the view to any contact or customer. All the texts are fully customable based on templates and i don't see why the layout shouldn't. So the main template should be easily editable.

However linking each netblocks/domains to a brand might need some extra thought. For example both items should resolve to the same contact for that brand, so just linking to contact model should suffice.

Next it would be a lot of work, whereas a company might only have 1 - 5 brands and usaelly with their own admins. Downsteaming abuseio into several instances with all their own settings would be a better choice in my opinion.

**Comment by kruisdraad** [comment]
implementation assigned for 4.0.0

**Comment by joverthegrey** [comment]
Verplaatst naar Youtrack
