### ISSUE TITLE
Prevent sending "Alert: There are x jobs that are stuck" every minute

### ISSUE THREAD

**Issue by hkraal** [AbuseIO/AbuseIO#55]
When jobs are stuck the "php /opt/abuseio/artisan schedule:run" cronjob will sent out an alert every minute which seems a bit excessive.

Perhaps you could put some threshold in place to prevent flooding mailboxes?

**Comment by kruisdraad** [comment]
true, however if you monitor supervisor and such your monitoring would pick this up and you only had a few e-mails. That said we could set the check interval less aggressively to 15 minutes or something.

what would be acceptable here?

**Comment by hkraal** [comment]
15 minutes is much less noisy, but even better would be a configurable option. Perhaps even a plug-in system could prove useful so your not bound to email notifications only. Using 15 minutes and email would be good default though.

**Comment by kruisdraad** [comment]
I've added an option to disable it entirely. The housekeeper can be changed in the cron settings, but its better if people would implement their own monitoring and this default monitoring would be something they could use until or instead of other monitoring is set up.

**Comment by kruisdraad** [comment]
16:18 < AbuseIO-GIT> [AbuseIO] kruisdraad pushed 1 new commit to master: https://git.io/vzi3g
16:18 < AbuseIO-GIT> AbuseIO/master d081a75 Bart Vrancken: add option to disable aggresive queue alerts
