### ISSUE TITLE
Unable to filter closed tickets

### ISSUE THREAD

**Issue by hkraal** [AbuseIO/AbuseIO#56]
So I tried to search for "Open" which yields 0 results, upon asking @kruisdraad he said:
```By default the field will search all columns for the value but the "Open" status equals to "1". Searching for "1" however will list all rows containing a "1" in one of the fields.```

Being able to filter on a specific column value ("Status: open") would be very convenient but for now the solution should make it possible to work trough only open tickets.

**Comment by kruisdraad** [comment]
should be resolved perhaps with a https://datatables.net/examples/api/multi_filter_select.html

allowing some additional selection filter pulldown's on non-freeform fields

**Comment by hkraal** [comment]
+ a sane default for this (status field) case. I think we can safely assume everyone initially would like to see check the current open tickets (Status Open or Escalated)?

**Comment by marknl** [comment]
Column filtering was implemented in b05d911b5452d994b431dc56aa67f211f5474f7e
