### ISSUE TITLE
Back button in admin/ticket/# view resolves to itself

### ISSUE THREAD

**Issue by hkraal** [AbuseIO/AbuseIO#57]
Reproduce with:
* Open ticket: /admin/tickets/5
* Change status to "Closed"
* Press "Back" and find yourself being directed to "/admin/tickets/5" instead of "/admin/tickets"

**Comment by kruisdraad** [comment]
because of back is redirecting to the visited url /admin/tickets/5/close

back should perhaps do a basename on the route?

**Comment by kruisdraad** [comment]
buttons removed, these were left over from the old search page.

as search has been replaced no need for this button
