### ISSUE TITLE
/admin/users/create doesn't save user

### ISSUE THREAD

**Issue by hkraal** [AbuseIO/AbuseIO#59]
When creating a user via the /admin/users/create page;

* It's not being saved to the DB
* Doesn't show an error when both password fields are empty
* If not already present; add a field to add roles to the user (as you cannot log in without assigned roles)

**Comment by kruisdraad** [comment]
the CLI has permissionAdd and roleAdd methods, this lacks on the GUI

**Comment by joverthegrey** [comment]
Ticket verplaatst naar abuseio youtrack
