### ISSUE TITLE
Show 'missing role' error on /auth/login

### ISSUE THREAD

**Issue by hkraal** [AbuseIO/AbuseIO#60]
If the user has no role(s) he will not be able to use his login. This isn't clear for the user as no error is being shown.

**Comment by kruisdraad** [comment]
[master 1947dd7] fix issue 60. the message was shown on the logout page which redirects back to the login page effectively you miss the message
 1 file changed, 5 insertions(+), 2 deletions(-)

**Comment by kruisdraad** [comment]
Fixed, please confirm if the problem is resolved

**Comment by hkraal** [comment]
Confirmed fix
