### ISSUE TITLE
Send the original subject on "Exception notification" mails

### ISSUE THREAD

**Issue by erdosip** [AbuseIO/AbuseIO#61]
I think that would be good, cause hard to seek mails back with a same subject. Maybe it shoud me a bool option in the config file...

**Comment by kruisdraad** [comment]
Yes indeed.

currently there is an ticket to explore and option to bounce the e-mails, however all existing php mail libraries do not have the option to bounce an e-mail sadly and proposed changes were not accepted by their upstream parties.

The Exception notification is not just for a failed e-mail, but also failed collection, hanging jobs, failed jobs, etc. Also using the original subject assumes you were able to parse the e-mail in the first place, however in some cases that would not be possible either.

So if your only interested in changing the format for the 'inbound mails' that failed, we could implement our own library to send the mail with a bounce. Once enabled you will get the original untouched mail in your mailbox as you were the recipient (we a resend-from header conform RFC)

Would that suffice?

**Comment by erdosip** [comment]
First of all, thanks for the fast reply! :)
And yes, I think your solution would be good to us, and maybe others too.

**Comment by kruisdraad** [comment]
Assignment started

p.s. join us on IRC, it would be better to interact there ;)

**Comment by kruisdraad** [comment]
Sadly this is not as easy as it looks. The whole reason for sending the alert is that the parsing failed. Using the subject or any other field suggests that parsing did work, so then we could just have handled the mail.

also PHPMailer does not respond anymore to the pull request and we're not really wanted to create and maintain a fork. If they adopt the change or we get a lot of demand for this feature we could perhaps rethink this.

For now we are not building this feature.
