### ISSUE TITLE
Date/Time repeatedly strtotime()'d in view

### ISSUE THREAD

**Issue by ihatehandles** [AbuseIO/AbuseIO#69]
The culprit is [this code](https://github.com/AbuseIO/AbuseIO/blob/master/app/Http/Requests/TicketFormRequest.php#L75):

```php
    if (strtotime($input['timestamp']) !== false) {
        $input['timestamp'] = strtotime($input['timestamp']);
    }

```

So the solution that involves the least amount of changing things is to solve the above which I've done, and then in the view we convert the timestamp field to a string with `date('Y-m-d H:i:s')`. This is the path of least friction that I can see. But also there's a little problem there. Laravel Form Builder has a set order of preference when considering what value to put in a field even when we specify what we want. It will look to old input first, and then consider the one we've provided. We want to override what's in the old input. A hack would be to create a helper function that simply overrides the old input, but I don't think we want hacks in the codebase?

So for now I'm engaging the maintainers of the Form Builder package to see if they can consider and accept my PR which enables us (as an option) to tell the Form Builder to use the value provided if we want that, and not to look for old input.

Whatever the end result will be, soon as we have this fixed I'll drop in the datepicker

**Comment by ihatehandles** [comment]
Anyway, the Form Builder solution will take a while to be in place. In the mean I've done something simpler (tell me if you like it and I'll send the PR): 

[https://github.com/ihatehandles/AbuseIO/tree/hotfix-timestamp-field-in-create-view](https://github.com/ihatehandles/AbuseIO/tree/hotfix-timestamp-field-in-create-view)

So instead of touching anything on the backend where everything's happy with an int timestamp, we only do the work on the frontend by using MomentJS to convert the timestamp to something our users can read and understand.

**Comment by kruisdraad** [comment]
Accepted into upstream with #73
