### ISSUE TITLE
Empty contacts shows DataTables error in 4.0.1

### ISSUE THREAD

**Issue by sndrsmnk** [AbuseIO/AbuseIO#88]
Fresh install of AbuseIO 4.0.1 on Ubuntu 16.04 (PHP7) without seeding the DB returns an AJAX error on the Contacts page: 

DataTables warning: table id=contacts-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by sndrsmnk** [comment]
Same error shows after (manually) creating a contact.

**Comment by kruisdraad** [comment]
ContactsController line 75 does a editColumn which does not exist on an empty object. If the array is empty, just return a empty datatable.

**Comment by kruisdraad** [comment]
confirmed fix
