### ISSUE TITLE
Housekeeper: Undefined offset: 0 on closing old tickets

### ISSUE THREAD

**Issue by dkoster** [AbuseIO/AbuseIO#95]
While working on the findcontact-custom addon, it seems a ticket has been created without an event.

framework.log shows:
`Apr 12 16:33:02 abuse abuseio[28613]: production.INFO: AbuseIO\Jobs\QueueTest: TestJob starting for queue abuseio_email_outgoing
Apr 12 16:33:02 abuse abuseio[28613]: production.INFO: AbuseIO\Jobs\QueueTest: TestJob completed for queue abuseio_email_outgoing
Apr 12 16:33:02 abuse abuseio[28615]: production.INFO: AbuseIO\Jobs\QueueTest: TestJob starting for queue abuseio_collector
Apr 12 16:33:02 abuse abuseio[28615]: production.INFO: AbuseIO\Jobs\QueueTest: TestJob completed for queue abuseio_collector
Apr 12 16:33:02 abuse abuseio[28973]: production.DEBUG: AbuseIO\Console\Commands\Housekeeper\RunCommand: KNOCK KNOCK! Housekeeping
Apr 12 16:33:02 abuse abuseio[28973]: production.INFO: AbuseIO\Console\Commands\Housekeeper\RunCommand: Housekeeper is starting queue checks
Apr 12 16:33:02 abuse abuseio[28973]: production.INFO: AbuseIO\Console\Commands\Housekeeper\RunCommand: Housekeeper is starting to close old tickets
Apr 12 16:33:04 abuse abuseio[28973]: production.ERROR: exception 'ErrorException' with message 'Undefined offset: 0' in /opt/abuseio/bootstrap/cache/compiled.php:12501 Stack trace: #0 /opt/abuseio/bootstrap/cache/compiled.php(12501): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', '/opt/abuseio/bo...', 12501, Array) #1 /opt/abuseio/app/Console/Commands/Housekeeper/RunCommand.php(261): Illuminate\Support\Collection->offsetGet(0) #2 /opt/abuseio/app/Console/Commands/Housekeeper/RunCommand.php(68): AbuseIO\Console\Commands\Housekeeper\RunCommand->ticketsClosing() #3 [internal function]: AbuseIO\Console\Commands\Housekeeper\RunCommand->handle() #4 /opt/abuseio/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array) #5 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array) #6 /opt/abuseio/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #7 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #8 /opt/abuseio/vendor/symfony/console/Application.php(841): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #9 /opt/abuseio/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(AbuseIO\Console\Commands\Housekeeper\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #10 /opt/abuseio/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #11 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #12 /opt/abuseio/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #13 {main}
Apr 12 16:33:05 abuse abuseio[28614]: production.INFO: AbuseIO\Jobs\QueueTest: TestJob starting for queue abuseio_email_incoming
Apr 12 16:33:05 abuse abuseio[28614]: production.INFO: AbuseIO\Jobs\QueueTest: TestJob completed for queue abuseio_email_incoming
Apr 12 16:33:05 abuse abuseio[28613]: production.INFO: AbuseIO\Jobs\QueueTest: TestJob starting for queue abuseio_email_outgoing
Apr 12 16:33:05 abuse abuseio[28613]: production.INFO: AbuseIO\Jobs\QueueTest: TestJob completed for queue abuseio_email_outgoing
Apr 12 16:33:05 abuse abuseio[28615]: production.INFO: AbuseIO\Jobs\QueueTest: TestJob starting for queue abuseio_collector
Apr 12 16:33:05 abuse abuseio[28615]: production.INFO: AbuseIO\Jobs\QueueTest: TestJob completed for queue abuseio_collector
`
When commenting the lines 261 through 269 in /opt/abuseio/app/Console/Commands/Housekeeper/RunCommand.php, it suppresses the error.

Quoting CrossWire:
16:33 <@CrossWire> problem is that cleanup assumes there are events to a ticket
                   and you managed to create one without it

**Comment by dkoster** [comment]
Did some digging around in the database and indeed found some tickets without any event:
SELECT t.id,t.class_id, e.ticket_id FROM tickets AS t LEFT JOIN events AS e ON (t.id=e.ticket_id) WHERE e.ticket_id IS NULL;

| 2594 | SSLV3_VULNERABLE_SERVER |      NULL |
| 2595 | SSLV3_VULNERABLE_SERVER |      NULL |
| 2596 | SSLV3_VULNERABLE_SERVER |      NULL |
| 2597 | SSLV3_VULNERABLE_SERVER |      NULL |
| 2598 | SSLV3_VULNERABLE_SERVER |      NULL |

And so on.

**Comment by kruisdraad** [comment]
This issue has been resolved with commit d80ba07 and will enter mainstream with the next release
