### ISSUE TITLE
Exception notification emails

### ISSUE THREAD

**Issue by ryanccarter** [AbuseIO/AbuseIO#96]
Brand new setup and getting email alerts. Any idea what is going on here?

Alert: There are 4700 jobs that are stuck:

`{"id":"1","queue":"abuseio_collector","payload":"{\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"data\":{\"command\":\"O:22:\\\"AbuseIO\\\\Jobs\\\\QueueTest\\\":3:{s:9:\\\"queueName\\\";s:17:\\\"abuseio_collector\\\";s:5:\\\"queue\\\";N;s:5:\\\"delay\\\";N;}\"}}","attempts":"0","reserved":"0","reserved_at":null,"available_at":"1460651404","created_at":"2016-04-14 16:30:04"}
{"id":"4","queue":"abuseio_collector","payload":"{\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"data\":{\"command\":\"O:22:\\\"AbuseIO\\\\Jobs\\\\QueueTest\\\":3:{s:9:\\\"queueName\\\";s:17:\\\"abuseio_collector\\\";s:5:\\\"queue\\\";N;s:5:\\\"delay\\\";N;}\"}}","attempts":"0","reserved":"0","reserved_at":null,"available_at":"1460651462","created_at":"2016-04-14 16:31:02"}
{"id":"7","queue":"abuseio_collector","payload":"{\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"data\":{\"command\":\"O:22:\\\"AbuseIO\\\\Jobs\\\\QueueTest\\\":3:{s:9:\\\"queueName\\\";s:17:\\\"abuseio_collector\\\";s:5:\\\"queue\\\";N;s:5:\\\"delay\\\";N;}\"}}","attempts":"0","reserved":"0","reserved_at":null,"available_at":"1460651521","created_at":"2016-04-14 16:32:01"}
{"id":"10","queue":"abuseio_collector","payload":"{\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"data\":{\"command\":\"O:22:\\\"AbuseIO\\\\Jobs\\\\QueueTest\\\":3:{s:9:\\\"queueName\\\";s:17:\\\"abuseio_collector\\\";s:5:\\\"queue\\\";N;s:5:\\\"delay\\\";N;}\"}}","attempts":"0","reserved":"0","reserved_at":null,"available_at":"1460651581","created_at":"2016-04-14 16:33:01"}
{"id":"13","queue":"abuseio_collector","payload":"{\"job\":\"Illuminate\\\\Queue\\\\CallQueuedHandler@call\",\"data\":{\"command\":\"O:22:\\\"AbuseIO\\\\Jobs\\\\QueueTest\\\":3:{s:9:\\\"queueName\\\";s:17:\\\"abuseio_collector\\\";s:5:\\\"queue\\\";N;s:5:\\\"delay\\\";N;}\"}}","attempts":"0","reserved":"0","reserved_at":null,"available_at":"1460651642","created_at":"2016-04-14 16:34:02"}`

**Comment by kruisdraad** [comment]
Please check https://docs.abuse.io/en/latest/common_problems/ item 1 and confirm its not a known (user) problem

**Comment by ryanccarter** [comment]
Sorry about that, I missed that page. I will check it out. Thanks!
